import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      items: ["intro"],
    },
    {
      type: "category",
      label: "Getting Started",
      items: ["getting-started/installation", "getting-started/configuration"],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "core-concepts/scoring-and-reputation",
        "core-concepts/ai-summaries",
        "core-concepts/architecture",
      ],
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        "advanced/automation",
        "advanced/frontend-src",
        "advanced/pipelines",
        "advanced/auth-worker",
      ],
    },
  ],
  api: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
